#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M
kotlin.native.binary.memoryModel=experimental
kotlin.incremental=false

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Ktor
io.ktor.development=true
kotlin.caching.enabled=false
